version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - JWT_SECRET_KEY=your-secret-key-change-in-production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  # 原有股票服务 (可选)
  a-stock:
    image: python:3.9-slim
    container_name: a-stock
    ports:
      - 5070:5070
    volumes:
      - stock:/app
    working_dir: /app
    command: ["sh", "start.sh"]
    restart: always

volumes:
  stock:
    external: true