version: '2'
services:
  a-stock:
    image: python:3.9-slim
    container_name: a-stock
    ports:
      - 5070:5070
    volumes:
      - stock:/app
    working_dir: /app
    command: ["sh", "start.sh"]
    restart: always

volumes:
  stock:
    external: true