version: '2'
services:
  a-stock:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    container_name: a-stock
    image: a-stock
    ports:
      - 5070:5070
